### PR TITLE
Build for linux/amd64, useful for local deployments

### PR DESCRIPTION
**Pull request by cquiroz**

### CODE REVIEW

**Comment by rpiaggio** [comment]
Do we want this on the deployments that go to testing and production or only for the ones on docker?

**Comment by cquiroz** [comment]
do we have a scenario wher we want another platform?

**Comment by rpiaggio** [comment]
> do we have a scenario wher we want another platform?

🤷  We'll find out eventually.

**Review by rpiaggio — APPROVED** [review]
LGTM

**Pull request merged**
